<?php
@define ('_chamsockhachhang','Chăm sóc khách hàng');
@define ('_lienhe','Liên hệ');
@define ('_gia','Giá');
@define ('_trangchu','Trang Chủ');
@define ('_gioithieu','Giới thiệu');
@define ('_sanpham','Sản Phẩm');
@define ('_tintuc','Tin Tức');
@define ('_dichvu','Dịch vụ');
@define ('_hosonangluc','Hồ sơ năng lực');
@define ('_chinhsach','Chính sách');
@define ('_sukien','Sự kiện');
@define ('_contactinfo','Thông tin liên hệ');
@define ('_timkiem','Tìm kiếm');
@define ('_danhmucsanpham','Danh mục sản phẩm');
@define ('_otherproduct','Sản phẩm khác');
@define ('_support','Hỗ trợ');
@define ('_othernews','Tin khác');
@define ('_hovaten','Họ tên');
@define ('_address','Địa chỉ');
@define ('_dienthoai','Điện thoại');
@define ('_chude','Chủ đề');
@define ('_noidung','Nội dung');
@define ('_captcha','Mã bảo vệ');
@define ('_gui','Gửi');
@define ('_reset','Làm lại');
@define ('_huongdansudung','Hướng dẫn sử dụng');
@define ('_thongsokythuat','Thông số kỹ thuật');
@define ('_dong','Đóng');
@define ('_taikhoan','Tài khoản');
@define ('_matkhau','Mật khẩu');
@define ('_xemthem','Xem thêm');
@define ('_masp','Mã sản phẩm');
@define ('_gia','Giá');
@define ('_anhsanpham','Ảnh sản phẩm');
@define ('_thongtinsanpham','Thông tin sản phẩm');
@define ('_binhluan','Bình luận');
@define ('_online','Đang Online');
@define ('_trongtuan','Trong tuần');
@define ('_homnay','Hôm qua');
@define ('_tongtruycap','Tổng Truy Cập');
@define ('_comingsoon','Đang cập nhật ....');
@define ('_designby','Thiết kế web');
@define ('_diachi2','Đ/c');
@define ('_hethongchinhanh','Hệ thống chi nhánh');
@define ('_tintucsukien','Tin tức - sự kiên');
@define ('_tinlienquan','Tin khác');
@define ('_tatca','Tất cả');
@define ('_sanphambanchay','Sản phẩm bán chạy');
@define ('_sanphamkhuyenmai','Sản phẩm khuyến mãi');
@define ('_nhaphoten','Nhập họ tên');
@define ('_sodienthoai','Số điện thoại');
@define ('_vuilongnhapnoidung','Vui lòng nhập nội dung');
@define ('_guithongtin','Gửi thông tin');
@define ('_vuilongdienthongtinbenduoi','Vui lòng điền thông tin phía dưới');
@define ('_formlienhe','From liên hệ');
@define ('_chinhsachcongty','Chính sách công ty');
@define ('_bocongthuong','Bộ công thương');
@define ('_vechungtoi','Về chúng tôi');
@define ('_themvaogiohang','Thêm vào giỏ hàng');
@define ('_giohang','Giỏ hàng');
@define ('_hotro247','Hỗ trợ khách hàng 24/7');
@define ('_soluong','Số lượng');
@define ('_thanhtien','Thành tiền');
@define ('_luotxem','Lượt xem');
@define ('_xuatsu','Xuất sứ');
@define ('_tinhthanhpho','Tỉnh/thành phố');
@define ('_quanhuyen','Quận/huyện');
@define ('_diachi','Địa chỉ');
@define ('_ghichu','Ghi chú');
@define ('_muatiep','Mua tiếp');
@define ('_thanhtoan','Thanh toán');
@define ('_xoa','Xóa');
@define ('_giohangrong','Không có sản phẩm nào trong giỏ hàng');
@define ('_noresult','Không tìm thấy kết quả nào theo tiêu chí tìm kiếm');
@define ('_khuyenmai','Khuyến mãi');
@define ('_mua','Mua');
@define ('_thongtinsanpham','Thông tin sản phẩm');
@define ('_sanphamlienquan','Sản phẩm liên quan');
@define ('_tinkhac','Tin Khác');


@define('_moda', 'Mỏ đá');
@define('_nhamaysanxuat', 'Nhà máy sản xuất');
@define('_congtrinh', 'Công trình');
@define('_bosuutap', 'Bộ sưu tập');
@define('_sanphamnoibat', 'Sản phẩm nổi bật');
@define('_hotrotructuyen', 'Hỗ trợ trực tuyến');
@define('_dangkynhantin', 'Đăng ký nhận tin');
@define('_guiyeucau', 'Gửi yêu cầu');
@define('_thongketruycap', 'Thống kê truy cập');