<?php
@define ('_chamsockhachhang','Customer care');
@define ('_lienhe','Contact');
@define ('_gia','Price');
@define ('_trangchu','Home page');
@define ('_gioithieu','Introduce');
@define ('_sanpham','Product');
@define ('_tintuc','News');
@define ('_dichvu','Service');
@define ('_hosonangluc','Capacity profile');
@define ('_chinhsach','Policy');
@define ('_sukien','Event');
@define ('_contactinfo','Contact Info');
@define ('_timkiem','Search');
@define ('_danhmucsanpham','Product portfolio');
@define ('_otherproduct','Other products');
@define ('_support','Support');
@define ('_othernews','Other news');
@define ('_hovaten','Name');
@define ('_address','Address');
@define ('_dienthoai','Phone');
@define ('_chude','Theme');
@define ('_noidung','Content');
@define ('_captcha','Security Code');
@define ('_gui','To send');
@define ('_reset','Rework, do it again');
@define ('_huongdansudung','User manual');
@define ('_thongsokythuat','Specifications');
@define ('_dong','Closed');
@define ('_taikhoan','Account');
@define ('_matkhau','Password');
@define ('_xemthem','Learn more');
@define ('_masp','Product code');
@define ('_gia','Price');
@define ('_anhsanpham','Image product');
@define ('_thongtinsanpham','Product information');
@define ('_binhluan','Comment');
@define ('_online','Online');
@define ('_trongtuan','In Week');
@define ('_homnay','Yesterday');
@define ('_tongtruycap','General Access');
@define ('_comingsoon','Updating ....');
@define ('_designby','Web design');
@define ('_diachi2','A / c');
@define ('_hethongchinhanh','Branch system');
@define ('_tintucsukien','News - events');
@define ('_tinlienquan','Other news');
@define ('_tatca','All');
@define ('_sanphambanchay','Selling products');
@define ('_sanphamkhuyenmai','Promotional Products');
@define ('_nhaphoten','Enter your name');
@define ('_sodienthoai','Phone number');
@define ('_vuilongnhapnoidung','Please enter the text');
@define ('_guithongtin','Send information');
@define ('_vuilongdienthongtinbenduoi','Please fill in the information below');
@define ('_formlienhe','From contact');
@define ('_chinhsachcongty','Company policy');
@define ('_bocongthuong','Ministry of Industry and Trade');
@define ('_vechungtoi','About us');
@define ('_themvaogiohang','Add in my bag');
@define ('_giohang','Cart');
@define ('_hotro247','Customer support 24/7');
@define ('_soluong','Amount');
@define ('_thanhtien','Into money');
@define ('_luotxem','View');
@define ('_xuatsu','Excerpts');
@define ('_tinhthanhpho','City / Province');
@define ('_quanhuyen','District');
@define ('_diachi','Address');
@define ('_ghichu','Note');
@define ('_muatiep','Buy next');
@define ('_thanhtoan','Pay');
@define ('_xoa','Erase');
@define ('_giohangrong','There are no products in your cart');
@define ('_noresult','No results were found by search criteria');
@define ('_khuyenmai','Promotion');
@define ('_mua','Buying');
@define ('_thongtinsanpham','Product information');
@define ('_sanphamlienquan','Related Products');
@define ('_tinkhac','Other news');


@define('_moda', 'Quarry');
@define('_nhamaysanxuat', 'Factory');
@define('_congtrinh', 'Construction');
@define('_bosuutap', 'Collection');
@define('_sanphamnoibat', 'Featured Products');
@define('_hotrotructuyen', 'Online support');
@define('_dangkynhantin', 'Sign up for');
@define('_guiyeucau', 'Send require');
@define('_thongketruycap', 'Statistical access');